import Image1 from "./img/img-1.png";
import Image2 from "./img/img-2.png";
import Image3 from "./img/img-3.png";
import Ai from "./img/ai.png";
import Ae from "./img/ae.png";
import Fi from "./img/fi.png";
import Me from "./img/me.png";
import Pr from "./img/pr.png";
import Ps from "./img/ps.png";
import Xd from "./img/xd.png";
import showcase from "./img/showcase.png";
export { Image1, Image2, Image3, Ai, Ae, Fi, Me, Pr, Ps, Xd, showcase };
